const fs = require('fs');
const path = require('path');

const POSTS_DIR = '_posts';
const OUTPUT_FILE = 'data/posts.js';

// Extract frontmatter from markdown file
function extractFrontmatter(content) {
    const frontmatterRegex = /^---\s*\n([\s\S]*?)\n---/;
    const match = content.match(frontmatterRegex);

    if (!match) return {};

    const frontmatter = {};
    const lines = match[1].split('\n');

    lines.forEach(line => {
        const colonIndex = line.indexOf(':');
        if (colonIndex > -1) {
            const key = line.substring(0, colonIndex).trim();
            let value = line.substring(colonIndex + 1).trim();

            if (value.startsWith('[') && value.endsWith(']')) {
                value = value.slice(1, -1).split(',').map(v => v.trim().replace(/['"]/g, ''));
            } else {
                value = value.replace(/^['"]|['"]$/g, '');
            }

            frontmatter[key] = value;
        }
    });

    return frontmatter;
}

// Parse date from filename (YYYY-MM-DD-title.md)
function parseDateFromFilename(filename) {
    const match = filename.match(/^(\d{4}-\d{2}-\d{2})/);
    return match ? match[1] : null;
}

// Parse all posts
function parsePosts() {
    if (!fs.existsSync(POSTS_DIR)) {
        console.error(`Posts directory "${POSTS_DIR}" not found`);
        return [];
    }

    const files = fs.readdirSync(POSTS_DIR)
        .filter(file => file.endsWith('.md'));

    const posts = files.map(file => {
        const content = fs.readFileSync(path.join(POSTS_DIR, file), 'utf-8');
        const frontmatter = extractFrontmatter(content);
        const date = parseDateFromFilename(file);
        const slug = file.replace('.md', '');

        return {
            slug,
            title: frontmatter.title || 'Untitled',
            date,
            tags: Array.isArray(frontmatter.tags) ? frontmatter.tags : [frontmatter.tags || 'uncategorized'],
            author: frontmatter.author || 'Keshav Santhanam'
        };
    });

    // Sort by date (newest first)
    posts.sort((a, b) => new Date(b.date) - new Date(a.date));

    return posts;
}

// Group posts by tag
function groupPostsByTag(posts) {
    const grouped = {};

    posts.forEach(post => {
        post.tags.forEach(tag => {
            if (!grouped[tag]) {
                grouped[tag] = [];
            }
            grouped[tag].push(post);
        });
    });

    return grouped;
}

// Generate posts.js file
function generatePostsJS() {
    const posts = parsePosts();
    const groupedPosts = groupPostsByTag(posts);

    // Create data directory if it doesn't exist
    const dataDir = path.dirname(OUTPUT_FILE);
    if (!fs.existsSync(dataDir)) {
        fs.mkdirSync(dataDir, { recursive: true });
    }

    const jsContent = `// Auto-generated by build.js - Do not edit manually
const postsData = ${JSON.stringify(groupedPosts, null, 2)};
`;

    fs.writeFileSync(OUTPUT_FILE, jsContent);
    console.log(`✓ Generated ${OUTPUT_FILE} with ${posts.length} posts`);
    console.log(`✓ Categories: ${Object.keys(groupedPosts).join(', ')}`);
}

// Run the build
try {
    generatePostsJS();
} catch (error) {
    console.error('Error generating posts:', error);
    process.exit(1);
}
